<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Features\Products\Commands\" />
    <Folder Include="Features\Products\DTOs\" />
    <Folder Include="Features\Products\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagement.Domain\InventoryManagement.Domain.csproj" />
  </ItemGroup>

</Project>
